apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mycluster
  region: ap-south-1

vpc:
  id: vpc-0c77ff3e485da7bf0
  subnets:
    private:
      ap-south-1a: { id: subnet-043349a539a0d86e3 }
      ap-south-1b: { id: subnet-00f0c06fdcb891c7e }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers, zone: private }
    instanceType: t2.micro
    desiredCapacity: 2
    privateNetworking: true

  - name: ng-2-builders
    labels: { role: builders, zone: private }
    instanceType: t2.micro
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
