apiVersion: v1
kind: Service
metadata:
  name: firstapp-service
  labels:
    app: FirstApp

spec:
  type: NodePort
  selector:
      app: FirstApp
  ports:
    - nodePort: 30613
      port: 8080
      targetPort: 8080