apiVersion: v1
kind: Service
metadata:
  name: first-app-service-np

spec:
  type: NodePort
  selector:
    app: FirstApp
  ports:
    - nodePort: 30613
      port: 8080
      targetPort: 8080